title: Alexandra's Photography
email: ola.szczerba@gmail.com
description: >- 
  A professional portfolio of Alexandra Szczerba's photography, featuring landscapes, portraits, and urban work.
baseurl: "/photography"
url: "http://alexandraszczerba.github.io"
theme: null
