title: Alexandra's Photography
email: your-email@example.com
description: >- 
  A professional portfolio of Alexandra Szczerba's photography, featuring landscapes, portraits, and urban work.
baseurl: "/photography-site"
url: "http://your-github-username.github.io"
